# Permalinks
#
# I'm not sure what pretty permalinks does
permalink:           pretty

# Setup
version: 1
title:               Briandk.com
tagline:             'Computing Education Research'
description:         ''
# url:                 http://Briandk.com
baseurl:             ''


# About/contact
author:
  name:              Brian Danielak
  url:               https://twitter.com/capbri
  email:             ''

# jekyll plugins
gems: [
  jekyll-gist
]
